//
//  UserTempData.swift
//  GithubUsers_Project
//
//  Created by Shayila Kamaal on 16/07/26.
//

import Foundation

//MARK: - WorkEdit Data

let tempData =
#"""
{ "total_count": 406094,
"incomplete_results": false,
"items": [
  {
    "id": 561730219,
    "node_id": "R_kgDOIXtSqw",
    "name": "hello-algo",
    "full_name": "krahets/hello-algo",
    "private": false,
    "owner": {
      "login": "krahets",
      "id": 26993056,
      "node_id": "MDQ6VXNlcjI2OTkzMDU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/26993056?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/krahets",
      "html_url": "https://github.com/krahets",
      "followers_url": "https://api.github.com/users/krahets/followers",
      "following_url": "https://api.github.com/users/krahets/following{/other_user}",
      "gists_url": "https://api.github.com/users/krahets/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/krahets/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/krahets/subscriptions",
      "organizations_url": "https://api.github.com/users/krahets/orgs",
      "repos_url": "https://api.github.com/users/krahets/repos",
      "events_url": "https://api.github.com/users/krahets/events{/privacy}",
      "received_events_url": "https://api.github.com/users/krahets/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/krahets/hello-algo",
    "description": "《Hello 算法》：动画图解、一键运行的数据结构与算法教程。支持简中、繁中、English、日本語，提供 Python, Java, C++, C, C#, JS, Go, Swift, Rust, Ruby, Kotlin, TS, Dart 等代码实现",
    "fork": false,
    "url": "https://api.github.com/repos/krahets/hello-algo",
    "forks_url": "https://api.github.com/repos/krahets/hello-algo/forks",
    "keys_url": "https://api.github.com/repos/krahets/hello-algo/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/krahets/hello-algo/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/krahets/hello-algo/teams",
    "hooks_url": "https://api.github.com/repos/krahets/hello-algo/hooks",
    "issue_events_url": "https://api.github.com/repos/krahets/hello-algo/issues/events{/number}",
    "events_url": "https://api.github.com/repos/krahets/hello-algo/events",
    "assignees_url": "https://api.github.com/repos/krahets/hello-algo/assignees{/user}",
    "branches_url": "https://api.github.com/repos/krahets/hello-algo/branches{/branch}",
    "tags_url": "https://api.github.com/repos/krahets/hello-algo/tags",
    "blobs_url": "https://api.github.com/repos/krahets/hello-algo/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/krahets/hello-algo/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/krahets/hello-algo/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/krahets/hello-algo/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/krahets/hello-algo/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/krahets/hello-algo/languages",
    "stargazers_url": "https://api.github.com/repos/krahets/hello-algo/stargazers",
    "contributors_url": "https://api.github.com/repos/krahets/hello-algo/contributors",
    "subscribers_url": "https://api.github.com/repos/krahets/hello-algo/subscribers",
    "subscription_url": "https://api.github.com/repos/krahets/hello-algo/subscription",
    "commits_url": "https://api.github.com/repos/krahets/hello-algo/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/krahets/hello-algo/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/krahets/hello-algo/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/krahets/hello-algo/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/krahets/hello-algo/contents/{+path}",
    "compare_url": "https://api.github.com/repos/krahets/hello-algo/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/krahets/hello-algo/merges",
    "archive_url": "https://api.github.com/repos/krahets/hello-algo/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/krahets/hello-algo/downloads",
    "issues_url": "https://api.github.com/repos/krahets/hello-algo/issues{/number}",
    "pulls_url": "https://api.github.com/repos/krahets/hello-algo/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/krahets/hello-algo/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/krahets/hello-algo/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/krahets/hello-algo/labels{/name}",
    "releases_url": "https://api.github.com/repos/krahets/hello-algo/releases{/id}",
    "deployments_url": "https://api.github.com/repos/krahets/hello-algo/deployments",
    "created_at": "2022-11-04T11:08:34Z",
    "updated_at": "2026-07-16T06:37:49Z",
    "pushed_at": "2026-04-18T18:23:33Z",
    "git_url": "git://github.com/krahets/hello-algo.git",
    "ssh_url": "git@github.com:krahets/hello-algo.git",
    "clone_url": "https://github.com/krahets/hello-algo.git",
    "svn_url": "https://github.com/krahets/hello-algo",
    "homepage": "https://www.hello-algo.com",
    "size": 464747,
    "stargazers_count": 128548,
    "watchers_count": 128548,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "has_discussions": true,
    "forks_count": 15423,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 38,
    "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": null,
      "node_id": "MDc6TGljZW5zZTA="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [
      "algo",
      "algorithm",
      "algorithms",
      "book",
      "data-structure",
      "data-structures",
      "data-structures-and-algorithms",
      "dsa",
      "education",
      "leetcode",
      "programming"
    ],
    "visibility": "public",
    "forks": 15423,
    "open_issues": 38,
    "watchers": 128548,
    "default_branch": "main",
    "score": 1.0
  },
  {
    "id": 14098069,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNDA5ODA2OQ==",
    "name": "free-programming-books-zh_CN",
    "full_name": "justjavac/free-programming-books-zh_CN",
    "private": false,
    "owner": {
      "login": "justjavac",
      "id": 359395,
      "node_id": "MDQ6VXNlcjM1OTM5NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/359395?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/justjavac",
      "html_url": "https://github.com/justjavac",
      "followers_url": "https://api.github.com/users/justjavac/followers",
      "following_url": "https://api.github.com/users/justjavac/following{/other_user}",
      "gists_url": "https://api.github.com/users/justjavac/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/justjavac/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/justjavac/subscriptions",
      "organizations_url": "https://api.github.com/users/justjavac/orgs",
      "repos_url": "https://api.github.com/users/justjavac/repos",
      "events_url": "https://api.github.com/users/justjavac/events{/privacy}",
      "received_events_url": "https://api.github.com/users/justjavac/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/justjavac/free-programming-books-zh_CN",
    "description": ":books: 免费的计算机编程类中文书籍，欢迎投稿",
    "fork": false,
    "url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN",
    "forks_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/forks",
    "keys_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/teams",
    "hooks_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/hooks",
    "issue_events_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/issues/events{/number}",
    "events_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/events",
    "assignees_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/assignees{/user}",
    "branches_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/branches{/branch}",
    "tags_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/tags",
    "blobs_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/languages",
    "stargazers_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/stargazers",
    "contributors_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/contributors",
    "subscribers_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/subscribers",
    "subscription_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/subscription",
    "commits_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/contents/{+path}",
    "compare_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/merges",
    "archive_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/downloads",
    "issues_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/issues{/number}",
    "pulls_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/labels{/name}",
    "releases_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/releases{/id}",
    "deployments_url": "https://api.github.com/repos/justjavac/free-programming-books-zh_CN/deployments",
    "created_at": "2013-11-04T01:59:19Z",
    "updated_at": "2026-07-16T05:09:56Z",
    "pushed_at": "2024-07-15T08:55:20Z",
    "git_url": "git://github.com/justjavac/free-programming-books-zh_CN.git",
    "ssh_url": "git@github.com:justjavac/free-programming-books-zh_CN.git",
    "clone_url": "https://github.com/justjavac/free-programming-books-zh_CN.git",
    "svn_url": "https://github.com/justjavac/free-programming-books-zh_CN",
    "homepage": "http://weibo.com/justjavac",
    "size": 1059,
    "stargazers_count": 117367,
    "watchers_count": 117367,
    "language": null,
    "has_issues": false,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 28209,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 33,
    "license": {
      "key": "gpl-3.0",
      "name": "GNU General Public License v3.0",
      "spdx_id": "GPL-3.0",
      "url": "https://api.github.com/licenses/gpl-3.0",
      "node_id": "MDc6TGljZW5zZTk="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [
      "android",
      "angular",
      "books",
      "free",
      "ios",
      "javascript",
      "kotlin",
      "pdf",
      "programming",
      "python",
      "react",
      "react-native",
      "swift",
      "vue"
    ],
    "visibility": "public",
    "forks": 28209,
    "open_issues": 33,
    "watchers": 117367,
    "default_branch": "main",
    "score": 1.0
  },
  {
    "id": 44838949,
    "node_id": "MDEwOlJlcG9zaXRvcnk0NDgzODk0OQ==",
    "name": "swift",
    "full_name": "swiftlang/swift",
    "private": false,
    "owner": {
      "login": "swiftlang",
      "id": 42816656,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjQyODE2NjU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/42816656?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/swiftlang",
      "html_url": "https://github.com/swiftlang",
      "followers_url": "https://api.github.com/users/swiftlang/followers",
      "following_url": "https://api.github.com/users/swiftlang/following{/other_user}",
      "gists_url": "https://api.github.com/users/swiftlang/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/swiftlang/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/swiftlang/subscriptions",
      "organizations_url": "https://api.github.com/users/swiftlang/orgs",
      "repos_url": "https://api.github.com/users/swiftlang/repos",
      "events_url": "https://api.github.com/users/swiftlang/events{/privacy}",
      "received_events_url": "https://api.github.com/users/swiftlang/received_events",
      "type": "Organization",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/swiftlang/swift",
    "description": "The Swift Programming Language",
    "fork": false,
    "url": "https://api.github.com/repos/swiftlang/swift",
    "forks_url": "https://api.github.com/repos/swiftlang/swift/forks",
    "keys_url": "https://api.github.com/repos/swiftlang/swift/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/swiftlang/swift/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/swiftlang/swift/teams",
    "hooks_url": "https://api.github.com/repos/swiftlang/swift/hooks",
    "issue_events_url": "https://api.github.com/repos/swiftlang/swift/issues/events{/number}",
    "events_url": "https://api.github.com/repos/swiftlang/swift/events",
    "assignees_url": "https://api.github.com/repos/swiftlang/swift/assignees{/user}",
    "branches_url": "https://api.github.com/repos/swiftlang/swift/branches{/branch}",
    "tags_url": "https://api.github.com/repos/swiftlang/swift/tags",
    "blobs_url": "https://api.github.com/repos/swiftlang/swift/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/swiftlang/swift/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/swiftlang/swift/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/swiftlang/swift/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/swiftlang/swift/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/swiftlang/swift/languages",
    "stargazers_url": "https://api.github.com/repos/swiftlang/swift/stargazers",
    "contributors_url": "https://api.github.com/repos/swiftlang/swift/contributors",
    "subscribers_url": "https://api.github.com/repos/swiftlang/swift/subscribers",
    "subscription_url": "https://api.github.com/repos/swiftlang/swift/subscription",
    "commits_url": "https://api.github.com/repos/swiftlang/swift/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/swiftlang/swift/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/swiftlang/swift/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/swiftlang/swift/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/swiftlang/swift/contents/{+path}",
    "compare_url": "https://api.github.com/repos/swiftlang/swift/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/swiftlang/swift/merges",
    "archive_url": "https://api.github.com/repos/swiftlang/swift/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/swiftlang/swift/downloads",
    "issues_url": "https://api.github.com/repos/swiftlang/swift/issues{/number}",
    "pulls_url": "https://api.github.com/repos/swiftlang/swift/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/swiftlang/swift/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/swiftlang/swift/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/swiftlang/swift/labels{/name}",
    "releases_url": "https://api.github.com/repos/swiftlang/swift/releases{/id}",
    "deployments_url": "https://api.github.com/repos/swiftlang/swift/deployments",
    "created_at": "2015-10-23T21:15:07Z",
    "updated_at": "2026-07-16T04:41:29Z",
    "pushed_at": "2026-07-16T05:01:42Z",
    "git_url": "git://github.com/swiftlang/swift.git",
    "ssh_url": "git@github.com:swiftlang/swift.git",
    "clone_url": "https://github.com/swiftlang/swift.git",
    "svn_url": "https://github.com/swiftlang/swift",
    "homepage": "https://swift.org",
    "size": 1361389,
    "stargazers_count": 70151,
    "watchers_count": 70151,
    "language": "Swift",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 10760,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 9099,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [

    ],
    "visibility": "public",
    "forks": 10760,
    "open_issues": 9099,
    "watchers": 70151,
    "default_branch": "main",
    "score": 1.0
  },
  {
    "id": 17803236,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNzgwMzIzNg==",
    "name": "rclone",
    "full_name": "rclone/rclone",
    "private": false,
    "owner": {
      "login": "rclone",
      "id": 24937341,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjI0OTM3MzQx",
      "avatar_url": "https://avatars.githubusercontent.com/u/24937341?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rclone",
      "html_url": "https://github.com/rclone",
      "followers_url": "https://api.github.com/users/rclone/followers",
      "following_url": "https://api.github.com/users/rclone/following{/other_user}",
      "gists_url": "https://api.github.com/users/rclone/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rclone/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rclone/subscriptions",
      "organizations_url": "https://api.github.com/users/rclone/orgs",
      "repos_url": "https://api.github.com/users/rclone/repos",
      "events_url": "https://api.github.com/users/rclone/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rclone/received_events",
      "type": "Organization",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/rclone/rclone",
    "description": "\"rsync for cloud storage\" - Google Drive, S3, Dropbox, Backblaze B2, One Drive, Swift, Hubic, Wasabi, Google Cloud Storage, Azure Blob, Azure Files, Yandex Files",
    "fork": false,
    "url": "https://api.github.com/repos/rclone/rclone",
    "forks_url": "https://api.github.com/repos/rclone/rclone/forks",
    "keys_url": "https://api.github.com/repos/rclone/rclone/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rclone/rclone/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rclone/rclone/teams",
    "hooks_url": "https://api.github.com/repos/rclone/rclone/hooks",
    "issue_events_url": "https://api.github.com/repos/rclone/rclone/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rclone/rclone/events",
    "assignees_url": "https://api.github.com/repos/rclone/rclone/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rclone/rclone/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rclone/rclone/tags",
    "blobs_url": "https://api.github.com/repos/rclone/rclone/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rclone/rclone/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rclone/rclone/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rclone/rclone/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rclone/rclone/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rclone/rclone/languages",
    "stargazers_url": "https://api.github.com/repos/rclone/rclone/stargazers",
    "contributors_url": "https://api.github.com/repos/rclone/rclone/contributors",
    "subscribers_url": "https://api.github.com/repos/rclone/rclone/subscribers",
    "subscription_url": "https://api.github.com/repos/rclone/rclone/subscription",
    "commits_url": "https://api.github.com/repos/rclone/rclone/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rclone/rclone/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rclone/rclone/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rclone/rclone/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rclone/rclone/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rclone/rclone/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rclone/rclone/merges",
    "archive_url": "https://api.github.com/repos/rclone/rclone/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rclone/rclone/downloads",
    "issues_url": "https://api.github.com/repos/rclone/rclone/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rclone/rclone/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rclone/rclone/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rclone/rclone/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rclone/rclone/labels{/name}",
    "releases_url": "https://api.github.com/repos/rclone/rclone/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rclone/rclone/deployments",
    "created_at": "2014-03-16T16:19:57Z",
    "updated_at": "2026-07-16T05:53:56Z",
    "pushed_at": "2026-07-15T17:05:29Z",
    "git_url": "git://github.com/rclone/rclone.git",
    "ssh_url": "git@github.com:rclone/rclone.git",
    "clone_url": "https://github.com/rclone/rclone.git",
    "svn_url": "https://github.com/rclone/rclone",
    "homepage": "https://rclone.org",
    "size": 249043,
    "stargazers_count": 58353,
    "watchers_count": 58353,
    "language": "Go",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 5211,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1185,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [
      "azure-blob",
      "azure-blob-storage",
      "azure-files",
      "backblaze-b2",
      "cloud-storage",
      "dropbox",
      "encryption",
      "ftp",
      "fuse-filesystem",
      "go",
      "golang",
      "google-cloud-storage",
      "google-drive",
      "onedrive",
      "openstack-swift",
      "rclone",
      "s3",
      "sftp",
      "sync",
      "webdav"
    ],
    "visibility": "public",
    "forks": 5211,
    "open_issues": 1185,
    "watchers": 58353,
    "default_branch": "master",
    "score": 1.0
  }
]
}
"""#
func formTempModal() -> GitHubList {
    let jsonData = tempData.data(using: .utf8)!
    let reponse = try? JSONDecoder().decode(GitHubList.self, from: jsonData)
    return reponse!
}


func formTempModalDetail() -> Repository {
    let jsonData = tempData.data(using: .utf8)!
    let reponse = try? JSONDecoder().decode(GitHubList.self, from: jsonData)
    return (reponse?.items[0])!    
}
